Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/AbcSize:
  Max: 16

Metrics/ClassLength:
  Max: 130

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 10

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'LICENSE.txt'
    - 'README.md'
    - 'Rakefile'
    - 'bitex.gemspec'
    - 'spec/**/*'
    - 'vendor/**/*'
